before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/redhat-developer/helm-dump/cmd.version={{.Version}}
      - -X github.com/redhat-developer/helm-dump/cmd.commit={{.Commit}}
      - -X github.com/redhat-developer/helm-dump/cmd.date={{.Date}}
      - -X github.com/redhat-developer/helm-dump/cmd.goVersion={{.Env.GOVERSION}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
