before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    id: helm-plugin
    binary: "{{ .Target }}/helm-dump"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
      - ppc64le
      - s390x
    ignore:
      - goos: windows
        goarch: "386"
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
      - -X github.com/redhat-developer/helm-dump/cmd.version={{.Version}}
      - -X github.com/redhat-developer/helm-dump/cmd.commit={{.Commit}}
      - -X github.com/redhat-developer/helm-dump/cmd.date={{.Date}}
      - -X github.com/redhat-developer/helm-dump/cmd.goVersion={{.Env.GOVERSION}}
  - env:
      - CGO_ENABLED=0
    id: crane-plugin
    main: ./plugins/helm_dump_init
    binary: "{{ .Target }}/crane-plugins/helm_dump_init"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
      - ppc64le
      - s390x
    ignore:
      - goos: windows
        goarch: "386"
      - goos: windows
        goarch: arm
archives:
  - format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^Initial commit$'
      - '^docs:'
      - '^test:'
      - '^chore:'
