name: release

on:
  push:


permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - uses: sergeysova/jq-action@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          cache: 'pip'
      - name: Set environment variables
        run: echo "GOVERSION=$(go env GOVERSION)" >> $GITHUB_ENV
      - name: Run tests
        run: make test
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: "!startsWith(github.ref, 'refs/tags')"
        with:
          distribution: goreleaser
          version: latest
          args: build --rm-dist --snapshot
      - name: Build Helm plugin
        run: make plugin
      - name: Publish Helm Dump plugin
        uses: actions/upload-artifact@v2
        with:
          name: helm-dump-plugin
          path: "dist/plugin/*"